---
- name: Create a new instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: ansible
    instance_type: t2.micro
    security_group: sg-123456 #needs to be created in AWS beforehand
    image: ami-123456 # this is the ami image id
    region: eu-west-1 # region where you want to create ec2 instance.
    subnet: subnet-123456 # subnet that is available in our AWS account (created automatically by AWS).
    groupname: webservers
  tasks:
  - name: Launch Instance
    ec2: 
      key_name: "{{ keypair }}"
      group_id: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: {{ subnet }}
      assign_public_ip: yes
    register: ec2
  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname={{ groupname }}
    with_items: "{{ ec2.instances }}"
  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"
  -name: configure new instance
   hosts: webservers
   sudo: yes # since AWS does not allow root we have enable sudo to root.
   remote_user: ubuntu
   gather_facts: True
  -include: nginx-ec2.yml

   
