---
- hosts: webservers
  tasks:
  - name: install nginx
    apt: name=nginx state=latest
  - name: ensure nginx is running (and enable it at boot)
    service: name=nnginx state=started enabled=yes
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted